### ISSUE TITLE
Travis tests for this repo sometimes fail because too many supported node versions cause travis to timeout

### ISSUE THREAD

**Issue by zdroid** [bevry/editions#17]
node 5 and 6 run travis CI build in 90 seconds, while older versions need more than 4 minutes. Having to run so many builds, network connection often fails: https://travis-ci.org/bevry/editions/builds/160781907.

Maybe you should drop support for 0.x versions, at least, it'd be far easier to maintain the project.

**Comment by balupton** [comment]
Unfortunately, one of the main reasons for writing editions was that we need to support node 0.10 for many of our modules - as certain enterprise systems use them, and up until recently meteor used them.

The failing tests is a valid concern, and we will need to figure out a way to solve this. I was chatting with Doug from express about this, and have a few ideas. The ideal seems to be to have travis share the node_modules directory across node versions so it doesn't need to bother with such time consuming installs. This could be a setup where we use nvm ourselves, rather than have travis do it for us. This would also solve the factor that build tools often do not run on old versions of node, despite our code doing so, so installing the tools and compiling and preparing on the latest node, then testing backwards each version, could work.

Open to ideas.

**Comment by balupton** [comment]
seems to have resolved itself

**Comment by zdroid** [comment]
It's really great when issues resolve themselves. :tada:
