### ISSUE TITLE
Clarify purpose of tool

### ISSUE THREAD

**Issue by jesstelford** [bevry/editions#6]
The `README.md` is very sparse - mostly linking out to other documents. It is always a good idea to have at least basic install / usage / goals in the `README.md` as it is shown by default on github.

I found the wiki page, but am still at a loss as to what exact problem `editions` is solving, or how to use it. After a couple of lengthy paragraphs, there was a table I skipped over, and I had to scroll way down to see any code, which wasn't immediately obvious what it did. I'm a busy engineer - make it super quick and easy for me to know why I should care about `editions` </devils advocate>

But seriously, I think I get the general idea behind `editions` - it allows setting up compile targets for different environments, yes? If so - what benefit does that give me over compiling everything down to the lowest common denominator (es5)? And if it is beneficial for me (smaller package size in the browser? Faster node startup time?), then how do I do that with the minimal amount of fuss?

**Comment by balupton** [comment]
Finish reading the page you skimmed over and get back to me.

**Comment by balupton** [comment]
To isolate.

Editions at its core is just a standardised `editions` property for your `package.json` file. This property defines the editions within your package. If anyone compiles their JavaScript code, they already have at least 2 editions, their source edition and their compiled edition.

Publishing only the source is great for bundlers and build tools (as they can do the best optimisations they can), but terrible for consumers as it nearly always (1) rules out older environments (2) requires compilation by the consumer either via their build tools or via runtime compilers

Publishing only the compiled is great for easy consumption, but terrible for runtime and bundlers. (1) Legacy code is running in situations where optimum "as close to the source as possible" code could be running. (2) Bundlers will need to compile already compiled code, which is never optimum.

By creating a standard for editions:

1. Producers can optionally inform consumers about the editions of their package via renderers like [projectz](https://github.com/bevry/projectz). Consumers can make intelligent choices about their consumption, and know more about the internals of the package quicker.

2. Producers can optionally tell the package to automatically load the best edition for the current environment via autoloaders like this package.

3. Producers can document their editions to inform consumers, and more easily standardise their build environments — even if they just publish the compiled tool - as consumers can be more aware about this — however, for the reasons stated earlier, publishing multiple editions is beneficial, as it offers consumers more control of which edition they load, it keeps to the optimum edition for the environment, and things like flow type still keep their information on the package.

So the reason why the README just directs to the wiki. Is because the package is the hub for the standard, while having code for the autoloader. It does not make sense to include information about either in the README, as it conflates the two.

The Wiki home and the Wiki FAQ currently goes into this, however ideally the FAQ should not be needed.

Editions serves as the successor to https://github.com/bevry/esnextguardian which already gets many downloads, without any standardisation of approaches, or informing consumers. With Editions, we have a solid foundation to consolidating the efforts of production and consumption - which will be very useful as tools like jspm, browserify, webpack, rollup, node es modules, flow type, come more into play.

**Comment by jesstelford** [comment]
> As this is the first day of Editions stability, you will have to bear with me. However, I foresee it becoming ever increasingly important as time goes by.

I hope it succeeds - I really like the idea (now that I've gotten it straight in my head).

> Editions serves as the successor to https://github.com/bevry/esnextguardian

The intro to `esnextguardian` is an excellent example _"[which made] it super quick and easy for me to know why I should care about [`esnextguardian`]"_.

Can I suggest a short intro in the README, with a slightly extended version as the intro on the wiki? Such as;

> `editions` is a new backwards compatible standard for describing the ways in which your code can be consumed. For example; by defining the entry points for your ES6 code, vs transpiled ES5, or; Coffeescript vs Javascript, etc.
>
> Using the [autoloader](#link-goes-here), other packages can automatically use the best version for the current execution environment.

Then with a slightly longer intro on the wiki, such as;

> `editions` is a new backwards compatible standard for describing the ways in which your code can be consumed.
> 
> Publishing only the source is great for bundlers and build tools, but terrible for consumers who might not be able to run it without compilation. Publishing only the compiled code is great for easy consumption, but terrible for runtime and bundlers who may introduce inefficiencies by re-compiling everything.
>
> `editions` allows you to publish both, and let the consumer decide which one to use.
>
> The first step is to add a configuration to your project's `package.json` file:
>
> ```json
  "editions": [
    {
      "description": "Source + ESNext + Require + Flow Type Comments",
      "entry": "source/index.js",
      "syntaxes": ["javascript", "esnext", "require", "arrows", "const", "let", "destructuring", "flow type comments"]
    }, {
      "description": "Babel Compiled + ES2015 + Require",
      "entry": "es2015/index.js",
      "syntaxes": ["javascript", "es2015", "require"]
    }
  ]
```
> 
> _Note: Editions are listed in descending order of preference. The most preferred edition to be loaded should be the first, which should be your source code._
>
> Next, either specify the default edition to be used via the regular `"main"` key in `package.json`:
>
> ```json
  "main": "es2015/index.js",
```
> 
> Or, (optionally) add an autoloader to pick the best version based on the environment;
>
> ```json
  "main": "index.js",
```
> 
> `index.js`
>   ``` javascript
  module.exports = require('editions').requirePackage(__dirname, require)
  ```

**Comment by balupton** [comment]
As a usage example, https://github.com/bevry/typechecker uses the `editions` property, and the autoloader, and projectz to update its README

**Comment by balupton** [comment]
Accomplished over at https://editions.bevry.me
